### ISSUE TITLE
Problem with nltk .download

### ISSUE THREAD

**Issue by idrissbachali** [AdrienGuille/TOM#10]
i m designing a web service including Topic modelling technique,so,i sue you code and i noticed that there is a problem with nltk .I m a beginer in natural language procesing and it is the first time that i met this problem.

In my terminal  shell ,it occurs that:
 File "C:\Users\IBL\.virtualenvs\python36env\lib\site-packages\nltk-3.4-py3.7-win32.egg\nltk\corpus\util.py", line 86, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, zip_name))
  File "C:\Users\IBL\.virtualenvs\python36env\lib\site-packages\nltk-3.4-py3.7-win32.egg\nltk\data.py", line 699, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  Attempted to load [93mcorpora/stopwords.zip/stopwords/[0m

  Searched in:
    - 'C:\\Users\\IBL/nltk_data'
    - 'C:\\Users\\IBL\\.virtualenvs\\python36env\\nltk_data'
    - 'C:\\Users\\IBL\\.virtualenvs\\python36env\\share\\nltk_data'
    - 'C:\\Users\\IBL\\.virtualenvs\\python36env\\lib\\nltk_data'
    - 'C:\\Users\\IBL\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_topic_model_browser.py", line 26, in <module>
    min_absolute_frequency=min_tf)
  File "C:\Users\IBL\desktop\Topic modelling\TOM\tom_lib\structure\corpus.py", line 41, in __init__
    stopWords = set(stopwords.words('french'))
  File "C:\Users\IBL\.virtualenvs\python36env\lib\site-packages\nltk-3.4-py3.7-win32.egg\nltk\corpus\util.py", line 123, in __getattr__
    self.__load()
  File "C:\Users\IBL\.virtualenvs\python36env\lib\site-packages\nltk-3.4-py3.7-win32.egg\nltk\corpus\util.py", line 88, in __load
    raise e
  File "C:\Users\IBL\.virtualenvs\python36env\lib\site-packages\nltk-3.4-py3.7-win32.egg\nltk\corpus\util.py", line 83, in __load
    root = nltk.data.find('{}/{}'.format(self.subdir, self.__name))
  File "C:\Users\IBL\.virtualenvs\python36env\lib\site-packages\nltk-3.4-py3.7-win32.egg\nltk\data.py", line 699, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource [93mstopwords[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('stopwords')
  [0m
  Attempted to load [93mcorpora/stopwords[0m

  Searched in:
    - 'C:\\Users\\IBL/nltk_data'
    - 'C:\\Users\\IBL\\.virtualenvs\\python36env\\nltk_data'
    - 'C:\\Users\\IBL\\.virtualenvs\\python36env\\share\\nltk_data'
    - 'C:\\Users\\IBL\\.virtualenvs\\python36env\\lib\\nltk_data'
    - 'C:\\Users\\IBL\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************
i use an approach that includes  to put in command line  
>>> import nltk
>>> nltk.download('stopwords')
But ,it doesn't work ,please help me!!!

**Comment by psorianom** [comment]
Are you running 
```
import nltk
nltk.download('stopwords')
```
from within your python command line? 
If you are, what error are you getting?

**Comment by idrissbachali** [comment]
yes, im running  this command line within my python ,but , it seems to be the same error as" Lookup error ".


i ve just fixed that with 👍 nltk.download() without " stopwords "
