### ISSUE TITLE
build_topic_model_browser.py

### ISSUE THREAD

**Issue by idrissbachali** [AdrienGuille/TOM#12]
i want to run this app build_topic_model_browser.py ,i got this unexpected error ,i noticed two errors "AttributeError: 'str' object has no attribute 'items'" and "TypeError: unhashable type: 'dict'"

Traceback (most recent call last):
  File "C:\Users\IBL\AppData\Local\Programs\Python\Python37-32\lib\site-packages\networkx\classes\function.py", line 649, in set_node_attributes
    for n, v in values.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_topic_model_browser.py", line 68, in <module>
    utils.save_json_object(corpus.collaboration_network(topic_associations[topic_id]),
  File "C:\Users\IBL\Desktop\Topic modelling\TOM\tom_lib\structure\corpus.py", line 153, in collaboration_network
    nx.set_node_attributes(nx_graph, 'betweenness', bb)
  File "C:\Users\IBL\AppData\Local\Programs\Python\Python37-32\lib\site-packages\networkx\classes\function.py", line 656, in set_node_attributes
    G.nodes[n][name] = values
TypeError: unhashable type: 'dict'

**Comment by AdrienGuille** [comment]
Hi,

Could you share more information about the corpus you're studying? Are the author lists specified in the CSV file?

Cheers,
Adrien

**Comment by idrissbachali** [comment]
hi ,
it 's french_corpus that includes many informations about law  ,legal text ..etc  ,it was cleaned and preproccessed  before i put it in inputs folder ,and the author list isn't specified .


So ,what can i do in this case?


Idris
