### ISSUE TITLE
data input

### ISSUE THREAD

**Issue by herrtao** [AdrienGuille/TOM#3]
is it possible to input plain text at the beginning of procession? or I have to transfer the plain text into CSV format? If so, is there any prerequisite for the format of CSV?

**Comment by RajaBellebon** [comment]
I tried to replicate the .csv in the example but I am getting an error:
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "thematic.py", line 22, in <module>
    use_corpus('/Users/rbellebon/Documents/Sta1/statement.csv')
  File "thematic.py", line 16, in use_corpus
    min_absolute_frequency=4)
  File "/usr/local/lib/python3.6/site-packages/tom_lib/structure/corpus.py", line 58, in __init__
    self.sklearn_vector_space = vectorizer.fit_transform(self.data_frame['text'].tolist())
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'text'`

**Comment by RajaBellebon** [comment]
after digging, you actually need to present the document like
id title text ...
0  xx   xxxx

**Comment by AdrienGuille** [comment]
Hi,

I updated the README file with infos regarding the formatting of the input file: https://github.com/AdrienGuille/TOM/blob/master/README.md#load-and-prepare-a-textual-corpus

Thanks for your comments
